// Importing createSlice from Redux Toolkit.
// createSlice simplifies creating Redux slices by combining actions and reducers automatically.
import { createSlice } from "@reduxjs/toolkit";

// Creating a "slice" of the Redux store for user-related state.
const userSlice = createSlice({
    // 'name' is used as a prefix for action types automatically generated by createSlice.
    name: "user",

    // 'initialState' defines the default state of this slice.
    // Here, we start with null because no user is logged in initially.
    initialState: null,

    // 'reducers' is an object where we define functions to handle state updates.
    reducers: {
        // addUser reducer: Updates the state with the user data sent in the action.
        // 'state' is the current state, 'action.payload' contains the new user data.
        addUser: (state, action) => {
            return action.payload; // returns new state (user object)
        },

        // removeUser reducer: Clears the user state (logs out the user).
        removeUser: (state, action) => {
            return null; // resets state to null
        }
    }
})

// Exporting the generated action creators for use in components.
// Corrected typo: 'addUser' not 'addUSer'.
export const { addUser, removeUser } = userSlice.actions;

// Exporting the reducer function to be added to the store.
// This reducer will handle user state changes based on dispatched actions.
export default userSlice.reducer;
